// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.

import {
  TypedMap,
  Entity,
  Value,
  ValueKind,
  store,
  Bytes,
  BigInt,
  BigDecimal
} from "@graphprotocol/graph-ts";

export class Factory extends Entity {
  constructor(id: string) {
    super();
    this.set("id", Value.fromString(id));

    this.set("engineCount", Value.fromBigInt(BigInt.zero()));
  }

  save(): void {
    let id = this.get("id");
    assert(id != null, "Cannot save Factory entity without an ID");
    if (id) {
      assert(
        id.kind == ValueKind.STRING,
        "Cannot save Factory entity with non-string ID. " +
          'Considering using .toHex() to convert the "id" to a string.'
      );
      store.set("Factory", id.toString(), this);
    }
  }

  static load(id: string): Factory | null {
    return changetype<Factory | null>(store.get("Factory", id));
  }

  get id(): string {
    let value = this.get("id");
    return value!.toString();
  }

  set id(value: string) {
    this.set("id", Value.fromString(value));
  }

  get engineCount(): BigInt {
    let value = this.get("engineCount");
    return value!.toBigInt();
  }

  set engineCount(value: BigInt) {
    this.set("engineCount", Value.fromBigInt(value));
  }
}

export class Token extends Entity {
  constructor(id: string) {
    super();
    this.set("id", Value.fromString(id));

    this.set("symbol", Value.fromString(""));
    this.set("name", Value.fromString(""));
    this.set("decimals", Value.fromBigInt(BigInt.zero()));
    this.set("totalSupply", Value.fromBigInt(BigInt.zero()));
  }

  save(): void {
    let id = this.get("id");
    assert(id != null, "Cannot save Token entity without an ID");
    if (id) {
      assert(
        id.kind == ValueKind.STRING,
        "Cannot save Token entity with non-string ID. " +
          'Considering using .toHex() to convert the "id" to a string.'
      );
      store.set("Token", id.toString(), this);
    }
  }

  static load(id: string): Token | null {
    return changetype<Token | null>(store.get("Token", id));
  }

  get id(): string {
    let value = this.get("id");
    return value!.toString();
  }

  set id(value: string) {
    this.set("id", Value.fromString(value));
  }

  get symbol(): string {
    let value = this.get("symbol");
    return value!.toString();
  }

  set symbol(value: string) {
    this.set("symbol", Value.fromString(value));
  }

  get name(): string {
    let value = this.get("name");
    return value!.toString();
  }

  set name(value: string) {
    this.set("name", Value.fromString(value));
  }

  get decimals(): BigInt {
    let value = this.get("decimals");
    return value!.toBigInt();
  }

  set decimals(value: BigInt) {
    this.set("decimals", Value.fromBigInt(value));
  }

  get totalSupply(): BigInt {
    let value = this.get("totalSupply");
    return value!.toBigInt();
  }

  set totalSupply(value: BigInt) {
    this.set("totalSupply", Value.fromBigInt(value));
  }
}

export class Pool extends Entity {
  constructor(id: string) {
    super();
    this.set("id", Value.fromString(id));

    this.set("createdAtTimestamp", Value.fromI32(0));
    this.set("createdAtBlockNumber", Value.fromI32(0));
    this.set("underlyingToken", Value.fromString(""));
    this.set("quoteToken", Value.fromString(""));
    this.set("strike", Value.fromBigInt(BigInt.zero()));
    this.set("strikeInt", Value.fromI32(0));
    this.set("sigma", Value.fromBigInt(BigInt.zero()));
    this.set("sigmaInt", Value.fromI32(0));
    this.set("maturity", Value.fromI32(0));
    this.set("gamma", Value.fromString(""));
    this.set("liquidity", Value.fromBigInt(BigInt.zero()));
    this.set("liquidityInt", Value.fromI32(0));
    this.set("txCount", Value.fromI32(0));
    this.set("totalUnderlyingTokens", Value.fromBigInt(BigInt.zero()));
    this.set("totalUnderlyingInt", Value.fromI32(0));
    this.set("totalQuoteTokens", Value.fromBigInt(BigInt.zero()));
    this.set("totalQuoteInt", Value.fromI32(0));
    this.set("liquidityProviderCount", Value.fromI32(0));
  }

  save(): void {
    let id = this.get("id");
    assert(id != null, "Cannot save Pool entity without an ID");
    if (id) {
      assert(
        id.kind == ValueKind.STRING,
        "Cannot save Pool entity with non-string ID. " +
          'Considering using .toHex() to convert the "id" to a string.'
      );
      store.set("Pool", id.toString(), this);
    }
  }

  static load(id: string): Pool | null {
    return changetype<Pool | null>(store.get("Pool", id));
  }

  get id(): string {
    let value = this.get("id");
    return value!.toString();
  }

  set id(value: string) {
    this.set("id", Value.fromString(value));
  }

  get createdAtTimestamp(): i32 {
    let value = this.get("createdAtTimestamp");
    return value!.toI32();
  }

  set createdAtTimestamp(value: i32) {
    this.set("createdAtTimestamp", Value.fromI32(value));
  }

  get createdAtBlockNumber(): i32 {
    let value = this.get("createdAtBlockNumber");
    return value!.toI32();
  }

  set createdAtBlockNumber(value: i32) {
    this.set("createdAtBlockNumber", Value.fromI32(value));
  }

  get underlyingToken(): string {
    let value = this.get("underlyingToken");
    return value!.toString();
  }

  set underlyingToken(value: string) {
    this.set("underlyingToken", Value.fromString(value));
  }

  get quoteToken(): string {
    let value = this.get("quoteToken");
    return value!.toString();
  }

  set quoteToken(value: string) {
    this.set("quoteToken", Value.fromString(value));
  }

  get strike(): BigInt {
    let value = this.get("strike");
    return value!.toBigInt();
  }

  set strike(value: BigInt) {
    this.set("strike", Value.fromBigInt(value));
  }

  get strikeInt(): i32 {
    let value = this.get("strikeInt");
    return value!.toI32();
  }

  set strikeInt(value: i32) {
    this.set("strikeInt", Value.fromI32(value));
  }

  get sigma(): BigInt {
    let value = this.get("sigma");
    return value!.toBigInt();
  }

  set sigma(value: BigInt) {
    this.set("sigma", Value.fromBigInt(value));
  }

  get sigmaInt(): i32 {
    let value = this.get("sigmaInt");
    return value!.toI32();
  }

  set sigmaInt(value: i32) {
    this.set("sigmaInt", Value.fromI32(value));
  }

  get maturity(): i32 {
    let value = this.get("maturity");
    return value!.toI32();
  }

  set maturity(value: i32) {
    this.set("maturity", Value.fromI32(value));
  }

  get gamma(): string {
    let value = this.get("gamma");
    return value!.toString();
  }

  set gamma(value: string) {
    this.set("gamma", Value.fromString(value));
  }

  get liquidity(): BigInt {
    let value = this.get("liquidity");
    return value!.toBigInt();
  }

  set liquidity(value: BigInt) {
    this.set("liquidity", Value.fromBigInt(value));
  }

  get liquidityInt(): i32 {
    let value = this.get("liquidityInt");
    return value!.toI32();
  }

  set liquidityInt(value: i32) {
    this.set("liquidityInt", Value.fromI32(value));
  }

  get txCount(): i32 {
    let value = this.get("txCount");
    return value!.toI32();
  }

  set txCount(value: i32) {
    this.set("txCount", Value.fromI32(value));
  }

  get totalUnderlyingTokens(): BigInt {
    let value = this.get("totalUnderlyingTokens");
    return value!.toBigInt();
  }

  set totalUnderlyingTokens(value: BigInt) {
    this.set("totalUnderlyingTokens", Value.fromBigInt(value));
  }

  get totalUnderlyingInt(): i32 {
    let value = this.get("totalUnderlyingInt");
    return value!.toI32();
  }

  set totalUnderlyingInt(value: i32) {
    this.set("totalUnderlyingInt", Value.fromI32(value));
  }

  get totalQuoteTokens(): BigInt {
    let value = this.get("totalQuoteTokens");
    return value!.toBigInt();
  }

  set totalQuoteTokens(value: BigInt) {
    this.set("totalQuoteTokens", Value.fromBigInt(value));
  }

  get totalQuoteInt(): i32 {
    let value = this.get("totalQuoteInt");
    return value!.toI32();
  }

  set totalQuoteInt(value: i32) {
    this.set("totalQuoteInt", Value.fromI32(value));
  }

  get liquidityProviderCount(): i32 {
    let value = this.get("liquidityProviderCount");
    return value!.toI32();
  }

  set liquidityProviderCount(value: i32) {
    this.set("liquidityProviderCount", Value.fromI32(value));
  }
}

export class Engine extends Entity {
  constructor(id: string) {
    super();
    this.set("id", Value.fromString(id));

    this.set("poolCount", Value.fromI32(0));
    this.set("pools", Value.fromStringArray(new Array(0)));
    this.set("underlyingToken", Value.fromString(""));
    this.set("txCount", Value.fromI32(0));
    this.set("quoteToken", Value.fromString(""));
    this.set("createdAtTimestamp", Value.fromBigInt(BigInt.zero()));
    this.set("createdAtBlockNumber", Value.fromBigInt(BigInt.zero()));
  }

  save(): void {
    let id = this.get("id");
    assert(id != null, "Cannot save Engine entity without an ID");
    if (id) {
      assert(
        id.kind == ValueKind.STRING,
        "Cannot save Engine entity with non-string ID. " +
          'Considering using .toHex() to convert the "id" to a string.'
      );
      store.set("Engine", id.toString(), this);
    }
  }

  static load(id: string): Engine | null {
    return changetype<Engine | null>(store.get("Engine", id));
  }

  get id(): string {
    let value = this.get("id");
    return value!.toString();
  }

  set id(value: string) {
    this.set("id", Value.fromString(value));
  }

  get poolCount(): i32 {
    let value = this.get("poolCount");
    return value!.toI32();
  }

  set poolCount(value: i32) {
    this.set("poolCount", Value.fromI32(value));
  }

  get pools(): Array<string> {
    let value = this.get("pools");
    return value!.toStringArray();
  }

  set pools(value: Array<string>) {
    this.set("pools", Value.fromStringArray(value));
  }

  get underlyingToken(): string {
    let value = this.get("underlyingToken");
    return value!.toString();
  }

  set underlyingToken(value: string) {
    this.set("underlyingToken", Value.fromString(value));
  }

  get txCount(): i32 {
    let value = this.get("txCount");
    return value!.toI32();
  }

  set txCount(value: i32) {
    this.set("txCount", Value.fromI32(value));
  }

  get quoteToken(): string {
    let value = this.get("quoteToken");
    return value!.toString();
  }

  set quoteToken(value: string) {
    this.set("quoteToken", Value.fromString(value));
  }

  get createdAtTimestamp(): BigInt {
    let value = this.get("createdAtTimestamp");
    return value!.toBigInt();
  }

  set createdAtTimestamp(value: BigInt) {
    this.set("createdAtTimestamp", Value.fromBigInt(value));
  }

  get createdAtBlockNumber(): BigInt {
    let value = this.get("createdAtBlockNumber");
    return value!.toBigInt();
  }

  set createdAtBlockNumber(value: BigInt) {
    this.set("createdAtBlockNumber", Value.fromBigInt(value));
  }
}

export class Position extends Entity {
  constructor(id: string) {
    super();
    this.set("id", Value.fromString(id));

    this.set("owner", Value.fromBytes(Bytes.empty()));
    this.set("pool", Value.fromString(""));
    this.set("underlyingToken", Value.fromString(""));
    this.set("quoteToken", Value.fromString(""));
    this.set("liquidity", Value.fromBigInt(BigInt.zero()));
    this.set("liquidityInt", Value.fromI32(0));
    this.set("depositedUnderlyingToken", Value.fromBigInt(BigInt.zero()));
    this.set("depositedUnderlyingStr", Value.fromString(""));
    this.set("depositedQuoteToken", Value.fromBigInt(BigInt.zero()));
    this.set("depositedQuoteInt", Value.fromI32(0));
    this.set("withdrawnUnderlyingToken", Value.fromBigInt(BigInt.zero()));
    this.set("withdrawnUnderlyingInt", Value.fromI32(0));
    this.set("withdrawnQuoteToken", Value.fromBigInt(BigInt.zero()));
    this.set("withdrawnQuoteInt", Value.fromI32(0));
  }

  save(): void {
    let id = this.get("id");
    assert(id != null, "Cannot save Position entity without an ID");
    if (id) {
      assert(
        id.kind == ValueKind.STRING,
        "Cannot save Position entity with non-string ID. " +
          'Considering using .toHex() to convert the "id" to a string.'
      );
      store.set("Position", id.toString(), this);
    }
  }

  static load(id: string): Position | null {
    return changetype<Position | null>(store.get("Position", id));
  }

  get id(): string {
    let value = this.get("id");
    return value!.toString();
  }

  set id(value: string) {
    this.set("id", Value.fromString(value));
  }

  get owner(): Bytes {
    let value = this.get("owner");
    return value!.toBytes();
  }

  set owner(value: Bytes) {
    this.set("owner", Value.fromBytes(value));
  }

  get pool(): string {
    let value = this.get("pool");
    return value!.toString();
  }

  set pool(value: string) {
    this.set("pool", Value.fromString(value));
  }

  get underlyingToken(): string {
    let value = this.get("underlyingToken");
    return value!.toString();
  }

  set underlyingToken(value: string) {
    this.set("underlyingToken", Value.fromString(value));
  }

  get quoteToken(): string {
    let value = this.get("quoteToken");
    return value!.toString();
  }

  set quoteToken(value: string) {
    this.set("quoteToken", Value.fromString(value));
  }

  get liquidity(): BigInt {
    let value = this.get("liquidity");
    return value!.toBigInt();
  }

  set liquidity(value: BigInt) {
    this.set("liquidity", Value.fromBigInt(value));
  }

  get liquidityInt(): i32 {
    let value = this.get("liquidityInt");
    return value!.toI32();
  }

  set liquidityInt(value: i32) {
    this.set("liquidityInt", Value.fromI32(value));
  }

  get depositedUnderlyingToken(): BigInt {
    let value = this.get("depositedUnderlyingToken");
    return value!.toBigInt();
  }

  set depositedUnderlyingToken(value: BigInt) {
    this.set("depositedUnderlyingToken", Value.fromBigInt(value));
  }

  get depositedUnderlyingStr(): string {
    let value = this.get("depositedUnderlyingStr");
    return value!.toString();
  }

  set depositedUnderlyingStr(value: string) {
    this.set("depositedUnderlyingStr", Value.fromString(value));
  }

  get depositedQuoteToken(): BigInt {
    let value = this.get("depositedQuoteToken");
    return value!.toBigInt();
  }

  set depositedQuoteToken(value: BigInt) {
    this.set("depositedQuoteToken", Value.fromBigInt(value));
  }

  get depositedQuoteInt(): i32 {
    let value = this.get("depositedQuoteInt");
    return value!.toI32();
  }

  set depositedQuoteInt(value: i32) {
    this.set("depositedQuoteInt", Value.fromI32(value));
  }

  get withdrawnUnderlyingToken(): BigInt {
    let value = this.get("withdrawnUnderlyingToken");
    return value!.toBigInt();
  }

  set withdrawnUnderlyingToken(value: BigInt) {
    this.set("withdrawnUnderlyingToken", Value.fromBigInt(value));
  }

  get withdrawnUnderlyingInt(): i32 {
    let value = this.get("withdrawnUnderlyingInt");
    return value!.toI32();
  }

  set withdrawnUnderlyingInt(value: i32) {
    this.set("withdrawnUnderlyingInt", Value.fromI32(value));
  }

  get withdrawnQuoteToken(): BigInt {
    let value = this.get("withdrawnQuoteToken");
    return value!.toBigInt();
  }

  set withdrawnQuoteToken(value: BigInt) {
    this.set("withdrawnQuoteToken", Value.fromBigInt(value));
  }

  get withdrawnQuoteInt(): i32 {
    let value = this.get("withdrawnQuoteInt");
    return value!.toI32();
  }

  set withdrawnQuoteInt(value: i32) {
    this.set("withdrawnQuoteInt", Value.fromI32(value));
  }
}
